# Generated by Django 3.2.9 on 2021-12-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='КАТЕГОРІЯ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ЗАГОЛОВОК')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='ТЕКСТ')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='ФОТО')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='ЧАС СТВОРЕННЯ')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='ЧАС ЗМІНИ')),
                ('is_published', models.BooleanField(default=True, verbose_name='ПУБЛІКАЦІЯ')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vts.category', verbose_name='КАТЕГОРІЯ')),
            ],
            options={
                'verbose_name': 'Викладачі',
                'verbose_name_plural': 'Викладачі',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
